[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  included_files = ["netlify/functions/**"]

# Enable edge functions if needed (optional)
# [edge_functions]
# included_files = ["netlify/edge-functions/**"]